apiVersion: apps/v1 
kind: Deployment
metadata:
  name: koatwo-server
  labels:
    server: koatwo
spec:
  selector:
    matchLabels:
      server: koatwo
  replicas: 2 
  template: 
    metadata:
      labels:
        server: koatwo
    spec:
      containers:
      - name: koatwo-server
        image: docker-registry.icarcloud.net:8088/server/koatwo-server:1.0.5
        ports:
        - containerPort: 7000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: koatwo-server
  labels:
    server: koatwo
spec:
  selector:
    server: koatwo
  type: NodePort
  # clusterIP: 10.106.100.2
  ports:
  - name: http
    protocol: TCP
    nodePort: 30004
    port: 7000
    targetPort: 7000
