apiVersion: apps/v1 
kind: Deployment
metadata:
  name: koatwo-server
  labels:
    server: koatwo-pods
spec:
  selector:
    matchLabels:
      server: koatwo-busi-server
  replicas: 2
  template: 
    metadata:
      labels:
        server: koatwo-busi-server
    spec:
      containers:
      - name: koatwo-server
        image: docker-registry.icarcloud.net:8088/server/koatwo-server:1.0.7
        ports:
        - containerPort: 7000
        volumeMounts:
          - name: secrets
            mountPath: "/etc/secrets"
            readOnly: true
      volumes:
        - name: secrets
          secret:
            secretName: mysecret

        
        
---

apiVersion: v1
kind: Service
metadata:
  name: koatwo-server
  labels:
    server: koatwo-service
spec:
  selector:
    server: koatwo-pods
  type: NodePort
  #clusterIP: 10.106.100.2
  ports:
  - name: http
    protocol: TCP
    nodePort: 30008
    port: 7009
    targetPort: 7008
