apiVersion: apps/v1 
kind: Deployment
metadata:
  name: koatwo-server
  labels:
    server: koatwo
spec:
  selector:
    matchLabels:
      server: koatwo
  replicas: 2 
  template: 
    metadata:
      labels:
        server: koatwo
    spec:
      containers:
      - name: koatwo-server
        image: docker-registry.icarcloud.net:8088/server/koatwoserver:1.0.0
        ports:
        - containerPort: 6702
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: koatwo-server
  labels:
    server: koatwo
spec:
  selector:
    server: koatwo
  type: NodePort
  # clusterIP: 10.106.100.2
  ports:
  - name: http
    protocol: TCP
    nodePort: 30003
    port: 6702
    targetPort: 6702
