-- MySQL Script generated by MySQL Workbench
-- 02/27/18 16:03:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema MemberCardServerDB
-- -----------------------------------------------------
-- 4S店CRM系统数据库
DROP SCHEMA IF EXISTS `MemberCardServerDB` ;

-- -----------------------------------------------------
-- Schema MemberCardServerDB
--
-- 4S店CRM系统数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MemberCardServerDB` DEFAULT CHARACTER SET utf8 ;
USE `MemberCardServerDB` ;

-- -----------------------------------------------------
-- Table `MemberCardServerDB`.`tradeOrders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MemberCardServerDB`.`tradeOrders` ;

CREATE TABLE IF NOT EXISTS `MemberCardServerDB`.`tradeOrders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(45) NULL,
  `sellOrderHref` VARCHAR(200) NULL COMMENT '销售订单链接。',
  `sellOrderUUID` VARCHAR(45) NULL COMMENT '销售订单UUID.',
  `merberCardHref` VARCHAR(200) NULL COMMENT '会员卡链接。',
  `merberCardUUID` VARCHAR(45) NULL COMMENT '会员卡UUID.',
  `isUseMemberCard` INT NULL COMMENT '是否使用会员卡来支付，',
  `tradeNumber` VARCHAR(45) NULL COMMENT '交易流水号。',
  `tradeAmount` DECIMAL(12,4) NULL COMMENT '交易总金额。',
  `tradeAt` TIMESTAMP(0) NULL COMMENT '交易时间。',
  `tradeAddress` VARCHAR(100) NULL COMMENT '交易地点。',
  `operator` VARCHAR(45) NULL COMMENT '操作人。',
  `status` VARCHAR(45) NULL COMMENT ' 状态分为   unpayed:初始状态(预支付)，partPayed:部分支付，全部支付，已取消，已关闭。',
  `remark` VARCHAR(200) NULL,
  `createdAt` TIMESTAMP(0) NULL,
  `modifiedAt` TIMESTAMP(0) NULL,
  PRIMARY KEY (`id`),
  INDEX `tradeOrder_MembercardUUIDidx_idx` (`merberCardUUID` ASC),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC))
ENGINE = InnoDB
COMMENT = '交易订单';


-- -----------------------------------------------------
-- Table `MemberCardServerDB`.`tradeObjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MemberCardServerDB`.`tradeObjects` ;

CREATE TABLE IF NOT EXISTS `MemberCardServerDB`.`tradeObjects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(45) NULL,
  `tradeOrderUUID` VARCHAR(45) NULL COMMENT '交易订单UUID.',
  `goodsHref` VARCHAR(200) NULL COMMENT '商品链接。',
  `goodsUUID` VARCHAR(45) NULL,
  `quatity` INT NULL COMMENT '数量。',
  `orignAmount` DECIMAL(12,4) NULL COMMENT '原始价。',
  `tradeAmount` DECIMAL(12,4) NULL COMMENT '交易金额。',
  `remark` VARCHAR(200) NULL,
  `status` VARCHAR(45) NULL COMMENT ' 状态分为初始状态(预支付)，部分支付，全部支付，已取消，已关闭。',
  `createdAt` TIMESTAMP(0) NULL,
  `modifiedAt` TIMESTAMP(0) NULL,
  PRIMARY KEY (`id`),
  INDEX `tradeObject_orderUUIDidx_idx` (`tradeOrderUUID` ASC),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC))
ENGINE = InnoDB
COMMENT = '交易商品对象';


-- -----------------------------------------------------
-- Table `MemberCardServerDB`.`tradeDetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MemberCardServerDB`.`tradeDetails` ;

CREATE TABLE IF NOT EXISTS `MemberCardServerDB`.`tradeDetails` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(45) NULL,
  `objectUUID` VARCHAR(45) NULL COMMENT '交易对象UUID.',
  `tradeAmount` DECIMAL(12,4) NULL COMMENT '交易金额。',
  `tradeNo` VARCHAR(45) NULL COMMENT '交易流水号。',
  `tradeSource` VARCHAR(200) NULL COMMENT '支付来源，包括会员卡的拥有服务链接，会员卡的账户链接，代金劵链接，现金等。',
  `tradeType` VARCHAR(45) NULL COMMENT '结算类型:包括服务次数扣除，储值扣除金额，代金劵扣除金额,现金支付。',
  `status` VARCHAR(45) NULL COMMENT ' 状态分为初始状态(预支付)，已支付，已取消，已关闭。',
  `remark` VARCHAR(200) NULL,
  `tradeAt` TIMESTAMP(0) NULL COMMENT '交易时间。',
  `createdAt` TIMESTAMP(0) NULL,
  `modifiedAt` TIMESTAMP(0) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC),
  INDEX `tradeDetail_objectuuididx_idx` (`objectUUID` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
