-- MySQL Script generated by MySQL Workbench
-- 03/09/18 14:30:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema MemberCardServerDB
-- -----------------------------------------------------
-- 4S店CRM系统数据库
DROP SCHEMA IF EXISTS `MemberCardServerDB` ;

-- -----------------------------------------------------
-- Schema MemberCardServerDB
--
-- 4S店CRM系统数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MemberCardServerDB` DEFAULT CHARACTER SET utf8 ;
USE `MemberCardServerDB` ;

-- -----------------------------------------------------
-- Table `MemberCardServerDB`.`memberCardTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MemberCardServerDB`.`memberCardTypes` ;

CREATE TABLE IF NOT EXISTS `MemberCardServerDB`.`memberCardTypes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(45) NULL,
  `name` VARCHAR(100) NULL COMMENT '卡类型名称。白金卡，白银卡。',
  `intergateRadio` DECIMAL(12,4) NULL COMMENT '积分系数。',
  `discountRadio` DECIMAL(12,4) NULL COMMENT '折扣比率。',
  `consumerAmountLimit` INT NULL COMMENT '消费额度达到此值时，才能升级成此类型卡。',
  `cardTypeNo` VARCHAR(45) NULL COMMENT '卡类型编号。',
  `createdAt` TIMESTAMP(0) NULL COMMENT '创建时间。',
  `modifiedAt` TIMESTAMP(0) NULL COMMENT '修改时间。',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC))
ENGINE = InnoDB
COMMENT = '会员卡类型。';


-- -----------------------------------------------------
-- Table `MemberCardServerDB`.`directorys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MemberCardServerDB`.`directorys` ;

CREATE TABLE IF NOT EXISTS `MemberCardServerDB`.`directorys` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `merchantHref` VARCHAR(200) NULL,
  `merchantUUID` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `description` VARCHAR(100) NULL,
  `createdAt` TIMESTAMP(0) NULL,
  `modifiedAt` TIMESTAMP(0) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC),
  UNIQUE INDEX `merchantUUID_UNIQUE` (`merchantUUID` ASC))
ENGINE = InnoDB
COMMENT = '会员卡目录 。';


-- -----------------------------------------------------
-- Table `MemberCardServerDB`.`memberCards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MemberCardServerDB`.`memberCards` ;

CREATE TABLE IF NOT EXISTS `MemberCardServerDB`.`memberCards` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(45) NULL,
  `directoryUUID` VARCHAR(45) NULL COMMENT '商户UUID.',
  `cardNo` VARCHAR(45) NULL COMMENT '会员卡号。',
  `name` VARCHAR(100) NULL COMMENT '姓名。',
  `phone` VARCHAR(100) NULL,
  `password` VARCHAR(100) NULL COMMENT '密码。',
  `email` VARCHAR(100) NULL COMMENT '邮箱。',
  `idCard` VARCHAR(100) NULL COMMENT '身份证号码。',
  `sex` VARCHAR(45) NULL COMMENT '性别。',
  `headImgURL` VARCHAR(200) NULL COMMENT '头像。',
  `openCardAt` TIMESTAMP(0) NULL COMMENT '开卡时间。',
  `beginAt` TIMESTAMP(0) NULL COMMENT '有效期开始时间。',
  `endAt` TIMESTAMP(0) NULL COMMENT '有效期结束时间。',
  `status` VARCHAR(45) NULL COMMENT '状态。normal:正常,lock:锁定，lost:挂失。',
  `cardTypeUUID` VARCHAR(45) NULL COMMENT '卡类型。',
  `consumerAmount` DECIMAL(12,4) NULL COMMENT '总消费额。',
  `ownerHref` VARCHAR(200) NULL COMMENT '拥有者链接。',
  `ownerUUID` VARCHAR(45) NULL COMMENT '拥有者UUID.',
  `createdAt` TIMESTAMP(0) NULL,
  `modifiedAt` TIMESTAMP(0) NULL COMMENT '修改时间。',
  PRIMARY KEY (`id`),
  INDEX `cardtypeUUIDidx_idx` (`cardTypeUUID` ASC),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC),
  INDEX `directoyUUIDcardidx_idx` (`directoryUUID` ASC),
  UNIQUE INDEX `cardNo_UNIQUE` (`cardNo` ASC),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC),
  UNIQUE INDEX `idCard_UNIQUE` (`idCard` ASC))
ENGINE = InnoDB
COMMENT = '会员卡信息。';


-- -----------------------------------------------------
-- Table `MemberCardServerDB`.`memberCardServices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MemberCardServerDB`.`memberCardServices` ;

CREATE TABLE IF NOT EXISTS `MemberCardServerDB`.`memberCardServices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(45) NULL,
  `memberCardUUID` VARCHAR(45) NULL COMMENT '会员卡UUID.',
  `serviceHref` VARCHAR(200) NULL COMMENT '商品服务链接。',
  `serviceUUID` VARCHAR(45) NULL COMMENT '服务UUID.',
  `serviceName` VARCHAR(100) NULL COMMENT '服务名称。如洗车。',
  `serviceType` VARCHAR(45) NULL COMMENT '服务类型，count:按次数，time:按时间。',
  `buyServiceValue` INT NULL COMMENT '拥有的服务次数,拥有50次洗车服务',
  `consumeredServiceValue` INT NULL COMMENT '已消费使用的服务，如已使用的服务次数，已使用3次洗车。',
  `source` VARCHAR(100) NULL COMMENT '服务来源。是从哪个商品订单转换而来。是指具体的商品订单。',
  `status` VARCHAR(45) NULL,
  `beginAt` TIMESTAMP(0) NULL COMMENT '有效期开始时间。',
  `endAt` TIMESTAMP(0) NULL COMMENT '有效期结束时间。',
  `createdAt` TIMESTAMP(0) NULL COMMENT '创建时间。',
  `modifiedAt` TIMESTAMP(0) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC),
  INDEX `servicemembercardUUIDiDX_idx` (`memberCardUUID` ASC))
ENGINE = InnoDB
COMMENT = '会员卡购买的服务。';


-- -----------------------------------------------------
-- Table `MemberCardServerDB`.`serviceRecords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MemberCardServerDB`.`serviceRecords` ;

CREATE TABLE IF NOT EXISTS `MemberCardServerDB`.`serviceRecords` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(45) NULL,
  `memberCardUUID` VARCHAR(45) NULL COMMENT '会员卡UUID.',
  `serviceUUID` VARCHAR(45) NULL COMMENT '操作内容。',
  `recordType` VARCHAR(45) NULL COMMENT '记录类型，如 buyService:购买服务，consumerService:消费服务。',
  `tradeValue` INT NULL COMMENT '交易值。',
  `leftValue` INT NULL COMMENT '剩余值。',
  `recordAt` TIMESTAMP(0) NULL COMMENT '记录时间。',
  `operator` VARCHAR(45) NULL COMMENT '操作人。',
  `recordSource` VARCHAR(200) NULL COMMENT '记录来源，是指来源于哪个商品订单。',
  `createdAt` TIMESTAMP(0) NULL COMMENT '创建时间。',
  `modifiedAt` TIMESTAMP(0) NULL COMMENT '修改时间。',
  PRIMARY KEY (`id`),
  INDEX `operatorRecordCardUUIDIdx_idx` (`memberCardUUID` ASC),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC))
ENGINE = InnoDB
COMMENT = '会员卡服务的交易记录。';


-- -----------------------------------------------------
-- Table `MemberCardServerDB`.`bankAccounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MemberCardServerDB`.`bankAccounts` ;

CREATE TABLE IF NOT EXISTS `MemberCardServerDB`.`bankAccounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(45) NULL,
  `memberCardHref` VARCHAR(200) NULL COMMENT '拥有者UUID.',
  `balanceAmount` DECIMAL(12,4) NULL COMMENT '账户余额。',
  `openAccountAt` TIMESTAMP(0) NULL COMMENT '开户时间。',
  `status` VARCHAR(45) NULL,
  `createdAt` TIMESTAMP(0) NULL,
  `modifiedAt` TIMESTAMP(0) NULL,
  `memberCardUUID` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC),
  INDEX `bankAccount_membercardUUIDiDX_idx` (`memberCardHref` ASC))
ENGINE = InnoDB
COMMENT = '储蓄账户。';


-- -----------------------------------------------------
-- Table `MemberCardServerDB`.`tradeRecords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MemberCardServerDB`.`tradeRecords` ;

CREATE TABLE IF NOT EXISTS `MemberCardServerDB`.`tradeRecords` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(45) NULL,
  `bankAccountUUID` VARCHAR(45) NULL COMMENT '账户UUID.',
  `tradeType` VARCHAR(45) NULL COMMENT '交易类型。income:收入，pay:支出',
  `tradeAmount` DECIMAL(12,4) NULL COMMENT '交易金额。',
  `balanceAmount` DECIMAL(12,4) NULL COMMENT '余额。',
  `tradeAt` TIMESTAMP(0) NULL COMMENT '交易时间。',
  `tradeNo` VARCHAR(45) NULL COMMENT '交易流水号。',
  `operator` VARCHAR(45) NULL COMMENT '操作人。',
  `status` VARCHAR(45) NULL,
  `remark` VARCHAR(255) NULL,
  `createdAt` TIMESTAMP(0) NULL,
  `modifiedAt` TIMESTAMP(0) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC),
  INDEX `tradeRecordAccountUUIDIDx_idx` (`bankAccountUUID` ASC))
ENGINE = InnoDB
COMMENT = '账户交易流水记录。';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
